// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieDatabase.Models;

namespace MovieDatabase.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20220127055605_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("MovieDatabase.Models.NewMovieResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Family",
                            Director = "Pierre Cofflin, Chris Renaud",
                            Edited = false,
                            MovieID = 0,
                            Rating = "PG",
                            Title = "Despicable Me",
                            Year = (ushort)2010
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Action/Sci-Fi",
                            Director = "Christopher Nolan",
                            Edited = false,
                            MovieID = 0,
                            Rating = "PG-13",
                            Title = "Inception",
                            Year = (ushort)2010
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Romance/Comedy",
                            Director = "Gil Junger",
                            Edited = false,
                            MovieID = 0,
                            Rating = "PG-13",
                            Title = "10 Things I Hate About You",
                            Year = (ushort)1999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
